### ISSUE TITLE
Content editor not working with Yoast-plugin 

### ISSUE THREAD

**Issue by Teleborg** [ThemeZee/tortuga#1]
In Combination with Yoast-SEO plugin the visual editor is not showing any content or saves changes to it. Only text editor is working. I tried also Gutenberg editor plugin, which also have issues to format content.

Other sites identify the problem in an old jQuery-ui library used by the theme.
WordPress 4.9.8
Theme Tortuga Version: 1.6
Yoast SEO plugin Version 7.9

**Comment by Netzberufler** [comment]
You have to check your other plugins. Tortuga does not embed and use the jQuery UI library. I have just checked and Yoast SEO works fine with Tortuga, we also have no reports from other users about any issues.
